/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 16-nov.-2022 8:19:21 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "JUGADOR_NUMEROS" CASCADE
;

/* Create Tables */

CREATE TABLE "JUGADOR_NUMEROS"
(
	num_sorteo numeric(3) NOT NULL,
	num_identificacion varchar(50) NULL,
	ide_premio numeric NULL,
	fec_registro timestamp without time zone NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "JUGADOR_NUMEROS" ADD CONSTRAINT "PK_USUARIO_NUMERO"
	PRIMARY KEY (num_sorteo)
;

CREATE INDEX "IXFK_USUARIO_NUMERO_PREMIO" ON "JUGADOR_NUMEROS" (ide_premio ASC)
;

CREATE INDEX "IXFK_USUARIO_NUMERO_USUARIO" ON "JUGADOR_NUMEROS" (num_identificacion ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "JUGADOR_NUMEROS" ADD CONSTRAINT "FK_USUARIO_NUMERO_PREMIO"
	FOREIGN KEY (ide_premio) REFERENCES "PREMIOS" (ide_premio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "JUGADOR_NUMEROS" ADD CONSTRAINT "FK_USUARIO_NUMERO_USUARIO"
	FOREIGN KEY (num_identificacion) REFERENCES "JUGADORES" (num_identificacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "JUGADOR_NUMEROS"
	IS 'Asignación de numero a usuarios, también se indica si ha sido ganador de premios y cual'
;
