/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 16-nov.-2022 8:17:56 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS ORGANIZACIONES CASCADE
;

/* Create Tables */

CREATE TABLE ORGANIZACIONES
(
	ide_organizacion varchar(50) NOT NULL,
        num_empleados numeric(1000,0),
	val_razon_social varchar(300) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE ORGANIZACIONES ADD CONSTRAINT "PK_ORGANIZACION"
	PRIMARY KEY (ide_organizacion)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE ORGANIZACIONES
	IS 'Hace referencia a la organización a la que pertenecen los usuario que participaran en el sorteo'
;
