/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 16-nov.-2022 8:18:50 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "PREMIOS" CASCADE
;

/* Create Tables */

CREATE TABLE "PREMIOS"
(
	ide_premio numeric NOT NULL,
	val_descripcion varchar(300) NULL,
	ide_organizacion varchar(50) NULL,
	val_activo boolean NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "PREMIOS" ADD CONSTRAINT "PK_PREMIO"
	PRIMARY KEY (ide_premio)
;

CREATE INDEX "IXFK_PREMIO_ORGANIZACION" ON "PREMIOS" (ide_organizacion ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "PREMIOS" ADD CONSTRAINT "FK_PREMIO_ORGANIZACION"
	FOREIGN KEY (ide_organizacion) REFERENCES "ORGANIZACIONES" (ide_organizacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "PREMIOS"
	IS 'Listado de premios '
;
